from fpdf import FPDF
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('Arial', 'B', 20)
        self.set_text_color(46, 125, 50)  # Agri-Green
        self.cell(0, 10, 'AgriTech AI - Digital Soil Health Card', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by AgriTech AI Intelligence System', 0, 0, 'C')

def generate_soil_report(data):
    pdf = PDFReport()
    pdf.add_page()
    
    # Report Date & Location
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Report Date: {datetime.now().strftime('%d %b %Y')}", 0, 1)
    pdf.cell(0, 10, f"Location: {data['location'].upper()}", 0, 1)
    pdf.ln(5)

    # Soil Table Header
    pdf.set_fill_color(46, 125, 50) 
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, " Soil Nutrient Analysis", 1, 1, 'L', fill=True)
    
    # Soil Data Rows
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(95, 10, f" Nitrogen (N): {data['n']} ppm", 1)
    pdf.cell(95, 10, f" Phosphorus (P): {data['p']} ppm", 1, 1)
    pdf.cell(95, 10, f" Potassium (K): {data['k']} ppm", 1)
    pdf.cell(95, 10, f" Soil pH: {data['ph']}", 1, 1)
    pdf.ln(10)

    # Prediction Section
    pdf.set_fill_color(232, 245, 233)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, " AI Prediction & Recommendation", 1, 1, 'L', fill=True)
    
    pdf.ln(5)
    pdf.set_font('Arial', 'B', 16)
    pdf.set_text_color(200, 0, 0) # Red for the crop name
    pdf.cell(0, 10, f"RECOMMENDED CROP: {data['crop']}", 0, 1, 'C')
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 11)
    pdf.ln(5)
    pdf.multi_cell(0, 10, f"Environmental Context: Temperature is {data['weather_temp']}C with {data['weather_desc']}.")
    
    # Advisory
    pdf.ln(5)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "AI Smart Advisory:", 0, 1)
    pdf.set_font('Arial', 'I', 11)
    pdf.multi_cell(0, 7, data['advice'])

    return pdf.output(dest='S').encode('latin-1')