import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def generate_soil_report(data):
    """Generates a PDF soil report using reportlab instead of fpdf"""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Header
    c.setFont("Helvetica-Bold", 20)
    c.setFillColorRGB(46/255.0, 125/255.0, 50/255.0) # Agri-Green
    c.drawCentredString(width/2.0, height - 50, 'AgriTech AI - Digital Soil Health Card')
    
    # Report Date & Location
    c.setFont("Helvetica-Bold", 12)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(50, height - 100, f"Report Date: {datetime.now().strftime('%d %b %Y')}")
    c.drawString(50, height - 120, f"Location: {data.get('location', 'N/A').upper()}")
    
    # Soil Data Row
    c.setFont("Helvetica-Bold", 14)
    c.setFillColorRGB(46/255.0, 125/255.0, 50/255.0)
    c.drawString(50, height - 160, "Soil Nutrient Analysis")
    
    c.setFont("Helvetica", 12)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(50, height - 190, f"Nitrogen (N): {data.get('n', '0')} ppm")
    c.drawString(300, height - 190, f"Phosphorus (P): {data.get('p', '0')} ppm")
    c.drawString(50, height - 210, f"Potassium (K): {data.get('k', '0')} ppm")
    c.drawString(300, height - 210, f"Soil pH: {data.get('ph', '0')}")
    
    # AI Prediction Section
    c.setFont("Helvetica-Bold", 14)
    c.setFillColorRGB(46/255.0, 125/255.0, 50/255.0)
    c.drawString(50, height - 260, "AI Prediction & Recommendation")
    
    c.setFont("Helvetica-Bold", 16)
    c.setFillColorRGB(200/255.0, 0, 0) # Red
    c.drawCentredString(width/2.0, height - 290, f"RECOMMENDED CROP: {data.get('crop', 'None')}")
    
    c.setFont("Helvetica", 11)
    c.setFillColorRGB(0, 0, 0)
    c.drawString(50, height - 330, f"Environmental Context: Temperature is {data.get('weather_temp', 'N/A')}C with {data.get('weather_desc', 'clear')}.")
    
    # Advisory
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 370, "AI Smart Advisory:")
    
    c.setFont("Helvetica-Oblique", 11)
    text = c.beginText(50, height - 390)
    
    # Simple text wrapping logic for the advisory
    words = str(data.get('advice', '')).split()
    line = ""
    for word in words:
        if len(line + word) > 95:
            text.textLine(line)
            line = word + " "
        else:
            line += word + " "
    text.textLine(line)
    c.drawText(text)
    
    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawCentredString(width/2.0, 30, f'Page 1 | Generated by AgriTech AI Intelligence System')
    
    c.save()
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes